[gamevals.dbtable]
instance_settings=65513

[gamevals.varp]
instance_state=65490

[gamevals.varbit]
pending_instance_row=65526

[gamevals.dbrow]
instance_amoxliatl=58000
instance_scurrius=64681
instance_kbd=64680
instance_cowboss=64679
instance_graardor=64594
instance_kreearra=64593
instance_zilyana=64592
instance_kril=64591
instance_vardorvis=63893