package org.rsmod.content.areas.city.varrock.museum

internal class NaturalHistoryQuestion(
    val text: String,
    val answers: List<String>,
    val correct: Int,
)

internal class NaturalHistoryModel(val component: String, val model: String)

internal class NaturalHistoryDisplay(
    val number: Int,
    val plaque: String,
    val varbit: String,
    val title: String,
    val models: List<NaturalHistoryModel>,
    val rotates: Boolean,
    val questions: List<NaturalHistoryQuestion>,
)

private fun question(text: String, correct: Int, vararg answers: String) =
    NaturalHistoryQuestion(text, answers.toList(), correct)

private fun model(name: String) =
    NaturalHistoryModel("component.vm_natural_history:vm_nathis_$name", "models.vm_nathis_$name")

internal val NaturalHistoryDisplays: List<NaturalHistoryDisplay> =
    listOf(
        NaturalHistoryDisplay(
            number = 1,
            plaque = "loc.vm_plaque_dragon",
            varbit = "varbit.vm_nathis_dragon_display",
            title = "The Dragon (Draconis Rex)",
            models = listOf(model("dragon_01"), model("dragon_02"), model("dragon_03")),
            rotates = false,
            questions =
                listOf(
                    question(
                        "What is considered a delicacy by dragons?",
                        1,
                        "Adventurers.",
                        "Runite.",
                        "Cheese.",
                    ),
                    question(
                        "What is the best defence against a dragon's attack?",
                        0,
                        "Anti dragon-breath shield.",
                        "Rune plate.",
                        "Cats.",
                    ),
                    question("How long do dragons live?", 2, "Fifty years.", "Forever.", "Unknown."),
                    question(
                        "Which of these is not a type of dragon?",
                        1,
                        "Coloured.",
                        "Elemental.",
                        "Ferrous.",
                    ),
                    question(
                        "What is the favoured territory of a dragon?",
                        1,
                        "Swamps.",
                        "Old battle sites.",
                        "Lumbridge Castle.",
                    ),
                    question(
                        "Approximately how many feet tall do dragons stand?",
                        0,
                        "Twelve.",
                        "Six.",
                        "Ten.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 2,
            plaque = "loc.vm_plaque_wyvern",
            varbit = "varbit.vm_nathis_wyvern_display",
            title = "The Wyvern (Draconis Ossis)",
            models = listOf(model("wyvern")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "How did the wyverns die out?",
                        0,
                        "Climate change.",
                        "Disease.",
                        "Marauding adventurers.",
                    ),
                    question("How many legs does a wyvern have?", 0, "Two.", "Five.", "Six."),
                    question(
                        "Where have wyvern bones been found?",
                        2,
                        "Ape Atoll.",
                        "Al Kharid.",
                        "Asgarnia.",
                    ),
                    question(
                        "Which genus does the wyvern theoretically belong to?",
                        1,
                        "Invertebrates.",
                        "Reptiles.",
                        "Mammals.",
                    ),
                    question(
                        "What are the wyverns' closest relations?",
                        2,
                        "Lizards.",
                        "Snakes.",
                        "Dragons.",
                    ),
                    question(
                        "What is the ambient temperature of wyvern bones?",
                        1,
                        "Room temperature.",
                        "Below room temperature.",
                        "Above room temperature.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 3,
            plaque = "loc.vm_plaque_battle_tortoise",
            varbit = "varbit.vm_nathis_tortoise_display",
            title = "The Giant Tortoise (Testudines Giganteus)",
            models = listOf(model("battle_tortoise")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "What is the name of the oldest tortoise ever recorded?",
                        1,
                        "Healthorg.",
                        "Mibbiwocket.",
                        "Snookums.",
                    ),
                    question(
                        "What is a tortoise's favourite food?",
                        2,
                        "Sharks.",
                        "Kebabs.",
                        "Vegetables.",
                    ),
                    question(
                        "Name the explorer who discovered the world's oldest tortoise.",
                        0,
                        "Admiral Bake.",
                        "Captain Cook.",
                        "Ensign Chef.",
                    ),
                    question(
                        "How does the tortoise protect itself?",
                        2,
                        "Thick skin.",
                        "Magic.",
                        "Hard shell.",
                    ),
                    question(
                        "If a tortoise had twenty rings on its shell, how old would it be?",
                        1,
                        "Ten years.",
                        "Twenty years.",
                        "Sixty years.",
                    ),
                    question(
                        "Which race breeds tortoises for battle?",
                        0,
                        "Gnomes.",
                        "Orks.",
                        "Elves.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 4,
            plaque = "loc.vm_plaque_lizard",
            varbit = "varbit.vm_nathis_lizard_display",
            title = "The Giant Lizard (Lacertilia Giganteus)",
            models = listOf(model("lizard")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "How does a lizard regulate body heat?",
                        2,
                        "Chilli sauce.",
                        "Fire.",
                        "Sunlight.",
                    ),
                    question(
                        "Who discovered how to kill lizards?",
                        1,
                        "Admiral Bake.",
                        "The Slayer Masters.",
                        "The Wise Old Man.",
                    ),
                    question("How many eyes does a lizard have?", 1, "Two.", "Three.", "Six."),
                    question(
                        "What order do lizards belong to?",
                        1,
                        "Mammal.",
                        "Squamata.",
                        "Insecta.",
                    ),
                    question(
                        "What happens when a lizard becomes cold?",
                        0,
                        "It becomes sleepy.",
                        "It becomes aggressive.",
                        "It explodes.",
                    ),
                    question(
                        "Lizard skin is made of the same substance as?",
                        0,
                        "Hair.",
                        "Bone.",
                        "Wood.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 5,
            plaque = "loc.vm_plaque_leech",
            varbit = "varbit.vm_nathis_leech_display",
            title = "The Giant Leech (Hirudinea Acidia)",
            models = listOf(model("leech")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "What is the favoured habitat of leeches?",
                        0,
                        "Water.",
                        "Desert.",
                        "Trees.",
                    ),
                    question(
                        "What shape is the inside of a leech's mouth?",
                        2,
                        "Star-shaped.",
                        "'X'-shaped.",
                        "'Y'-shaped.",
                    ),
                    question(
                        "Which of these is not eaten by leeches?",
                        1,
                        "Meat.",
                        "Apples.",
                        "Blood.",
                    ),
                    question(
                        "What contributed to the giant growth of Morytanian leeches?",
                        0,
                        "Environment.",
                        "Healthy living.",
                        "Magic.",
                    ),
                    question(
                        "What is special about Morytanian leeches?",
                        1,
                        "They sing.",
                        "They attack by jumping.",
                        "They have legs.",
                    ),
                    question(
                        "How does a leech change when it feeds?",
                        2,
                        "It turns blue.",
                        "It starts singing.",
                        "It doubles in size.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 6,
            plaque = "loc.vm_plaque_camel",
            varbit = "varbit.vm_nathis_camel_display",
            title = "The Camel (Camelus Bactrian)",
            models = listOf(model("camel")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "What is produced by feeding chilli to a camel?",
                        1,
                        "An irate camel.",
                        "Toxic dung.",
                        "An undead bactrian.",
                    ),
                    question(
                        "If an ugthanki has one, how many does a bactrian have?",
                        1,
                        "One.",
                        "Two.",
                        "Four.",
                    ),
                    question(
                        "Camels: herbivore, carnivore or omnivore?",
                        2,
                        "Herbivore.",
                        "Carnivore.",
                        "Omnivore.",
                    ),
                    question(
                        "What is the usual mood for a camel?",
                        0,
                        "Annoyed.",
                        "Bemused.",
                        "Cheerful.",
                    ),
                    question(
                        "Where would you find an ugthanki?",
                        0,
                        "Al Kharid.",
                        "Morytania.",
                        "Nowhere.",
                    ),
                    question(
                        "Which camel byproduct is known to be very nutritious?",
                        0,
                        "Milk.",
                        "Dung.",
                        "Meat.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 7,
            plaque = "loc.vm_plaque_mole",
            varbit = "varbit.vm_nathis_mole_display",
            title = "The Giant Mole (Talpidae Wysonian)",
            models = listOf(model("mole")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "What habitat do moles prefer?",
                        0,
                        "Subterranean.",
                        "Any.",
                        "Subaquatic.",
                    ),
                    question(
                        "Why are moles considered to be an agricultural pest?",
                        0,
                        "They dig holes.",
                        "They eat food meant for livestock.",
                        "They attack farmers.",
                    ),
                    question(
                        "Who discovered giant moles?",
                        2,
                        "Sir Tiffy Cashien.",
                        "Ak-Haranu.",
                        "Wyson the Gardener.",
                    ),
                    question(
                        "What would you call a group of young moles?",
                        2,
                        "A litter.",
                        "A mess.",
                        "A labour.",
                    ),
                    question(
                        "What is a mole's favourite food?",
                        0,
                        "Insects and other invertebrates.",
                        "Humans and gnomes.",
                        "Seeds and plant roots.",
                    ),
                    question(
                        "Which family do moles belong to?",
                        1,
                        "The Malpidae family.",
                        "The Talpidae family.",
                        "The Falpidae family.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 8,
            plaque = "loc.vm_plaque_penguine",
            varbit = "varbit.vm_nathis_penguin_display",
            title = "The Penguin (Spheniscidae Callidus)",
            models = listOf(model("penguine")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "Which sense do penguins rely on when hunting?",
                        2,
                        "Smell.",
                        "Taste.",
                        "Sight.",
                    ),
                    question(
                        "Which skill seems unusual for the penguins to possess?",
                        0,
                        "Planning.",
                        "Fishing.",
                        "Sleeping.",
                    ),
                    question(
                        "How do penguins keep warm?",
                        0,
                        "A layer of fat.",
                        "Vigorous exercise.",
                        "Magic.",
                    ),
                    question(
                        "What is the preferred climate for penguins?",
                        0,
                        "Cold.",
                        "Hot.",
                        "Damp.",
                    ),
                    question(
                        "Describe the behaviour of penguins?",
                        0,
                        "Social.",
                        "Asocial.",
                        "Hive.",
                    ),
                    question(
                        "When do penguins fast?",
                        1,
                        "Just before dawn.",
                        "During breeding.",
                        "During the night.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 9,
            plaque = "loc.vm_plaque_terrorbird",
            varbit = "varbit.vm_nathis_terrorbird_display",
            title = "The Terrorbird (Aves Terror)",
            models = listOf(model("terrorbird")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "What is a terrorbird's preferred food?",
                        0,
                        "Anything.",
                        "Pizza.",
                        "Vegetables.",
                    ),
                    question(
                        "Who use terrorbirds as mounts?",
                        1,
                        "Dwarves.",
                        "Gnomes.",
                        "Goblins.",
                    ),
                    question(
                        "Where do terrorbirds get most of their water?",
                        2,
                        "Streams and rivers.",
                        "Licking trees.",
                        "Eating plants.",
                    ),
                    question("How many claws do terrorbirds have?", 1, "Two.", "Four.", "Six."),
                    question(
                        "What do terrorbirds eat to aid digestion?",
                        1,
                        "Blurite.",
                        "Stones.",
                        "Paper.",
                    ),
                    question("How many teeth do terrorbirds have?", 2, "28.", "14.", "0."),
                ),
        ),
        NaturalHistoryDisplay(
            number = 10,
            plaque = "loc.vm_plaque_kalphite_queen",
            varbit = "varbit.vm_nathis_kalphite_display",
            title = "The Kalphite Queen (Kalphiscarabeinae Pasha)",
            models = listOf(model("kalphite_queen")),
            rotates = true,
            questions =
                listOf(
                    question("Kalphites are ruled by a...?", 1, "King.", "Pasha.", "Caliph."),
                    question(
                        "What is the lowest caste in kalphite society?",
                        2,
                        "Prince.",
                        "Soldier.",
                        "Worker.",
                    ),
                    question(
                        "What are the armoured plates on a kalphite called?",
                        1,
                        "Hauberk.",
                        "Lamellae.",
                        "Shield.",
                    ),
                    question(
                        "Are kalphites carnivores, herbivores or omnivores?",
                        2,
                        "Omnivores.",
                        "Herbivores.",
                        "Carnivores.",
                    ),
                    question(
                        "What are kalphites assumed to have evolved from?",
                        0,
                        "Scarab beetles.",
                        "Penguins.",
                        "Dragons.",
                    ),
                    question(
                        "Name the prominent figure in kalphite mythology?",
                        1,
                        "Postie Pete.",
                        "Scabaras.",
                        "Jorral the Historian.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 11,
            plaque = "loc.vm_plaque_monkey",
            varbit = "varbit.vm_nathis_monkey_display",
            title = "The Monkey (Simiiformes Karamjan)",
            models = listOf(model("monkey")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "Which type of primates do monkeys belong to?",
                        0,
                        "Simian.",
                        "Hominid.",
                        "Lagomorpha.",
                    ),
                    question(
                        "Which have the lighter colour: Karamjan or Harmless monkeys?",
                        2,
                        "They are the same.",
                        "Karamjan.",
                        "Harmless.",
                    ),
                    question(
                        "Monkeys love bananas. What else do they like to eat?",
                        2,
                        "Chilli.",
                        "Seaweed.",
                        "Bitternuts.",
                    ),
                    question(
                        "There are two known families of monkeys. One is Karamjan, the other is...?",
                        1,
                        "Pointless.",
                        "Harmless.",
                        "Hairless.",
                    ),
                    question(
                        "What colour mohawk do Karamjan monkeys have?",
                        0,
                        "Red.",
                        "Blue.",
                        "Green.",
                    ),
                    question(
                        "What have Karamjan monkeys taken a deep dislike to?",
                        0,
                        "Seaweed.",
                        "Chilli.",
                        "Taxes.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 12,
            plaque = "loc.vm_plaque_seaslug",
            varbit = "varbit.vm_nathis_seaslug_display",
            title = "The Sea Slug (Opisthobranchia Alucinor)",
            models =
                listOf(
                    model("seaslugs_1"),
                    model("seaslugs_2"),
                    model("seaslugs_3"),
                    model("seaslugs_4"),
                ),
            rotates = false,
            questions =
                listOf(
                    question(
                        "We assume that sea slugs have a stinging organ on their soft skin - " +
                            "what is it called?",
                        0,
                        "Nematocysts.",
                        "Hematocysts.",
                        "Pematocysts.",
                    ),
                    question(
                        "Why has the museum never examined a live sea slug?",
                        1,
                        "The sea slugs are shy.",
                        "The researchers keep vanishing.",
                        "Sea slugs are extinct.",
                    ),
                    question(
                        "What do we think the sea slug feeds upon?",
                        1,
                        "Blood.",
                        "Seaweed.",
                        "Insects.",
                    ),
                    question(
                        "What are the two fangs presumed to be used for?",
                        0,
                        "Defence or display.",
                        "Attacking prey.",
                        "Latching on to objects.",
                    ),
                    question(
                        "Off of which coastline would you find sea slugs?",
                        2,
                        "Karamja.",
                        "Miscellania.",
                        "Ardougne.",
                    ),
                    question(
                        "In what way are sea slugs similar to snails?",
                        2,
                        "They eat lettuce.",
                        "They move very slowly.",
                        "They have a hard shell.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 13,
            plaque = "loc.vm_plaque_snake",
            varbit = "varbit.vm_nathis_snake_display",
            title = "The Snake (Serpentes Fellis)",
            models = listOf(model("snake")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "What is snake venom adapted from?",
                        1,
                        "Ear wax.",
                        "Stomach acid.",
                        "Saliva.",
                    ),
                    question(
                        "Aside from their noses, what do snakes use to smell?",
                        0,
                        "Tongue.",
                        "Eyes.",
                        "Ears.",
                    ),
                    question(
                        "If a snake sticks its tongue out at you, what is it doing?",
                        2,
                        "Being rude.",
                        "Seeing how you taste.",
                        "Seeing how you smell.",
                    ),
                    question(
                        "If some snakes use venom to kill their prey, what do other snakes use?",
                        1,
                        "Fire.",
                        "Constriction.",
                        "Magic.",
                    ),
                    question(
                        "Lizards and snakes belong to the same order - what is it?",
                        0,
                        "Squamata.",
                        "Insecta.",
                        "Sarcopterghii.",
                    ),
                    question(
                        "Which habitat do snakes prefer?",
                        2,
                        "The desert.",
                        "The ocean.",
                        "Anywhere.",
                    ),
                ),
        ),
        NaturalHistoryDisplay(
            number = 14,
            plaque = "loc.vm_plaque_snail",
            varbit = "varbit.vm_nathis_snail_display",
            title = "The Giant Snail (Achatina Acidia Giganteus)",
            models = listOf(model("snail")),
            rotates = true,
            questions =
                listOf(
                    question(
                        "What is special about the shell of the giant Morytanian snail?",
                        2,
                        "It glows in the dark.",
                        "It is very tasty.",
                        "It is resistant to acid.",
                    ),
                    question(
                        "How do Morytanian snails capture their prey?",
                        1,
                        "Aggressive marketing.",
                        "Spitting acid.",
                        "Hex them until they glow.",
                    ),
                    question(
                        "Which of these is a snail byproduct?",
                        0,
                        "Fireproof oil.",
                        "A musical instrument",
                        "Snail-a-cola.",
                    ),
                    question(
                        "What does 'Achatina Acidia' mean?",
                        1,
                        "Giant acid-spitting snail.",
                        "Acid-spitting snail.",
                        "Giant cheese-spitting snail.",
                    ),
                    question(
                        "How do snails move?",
                        1,
                        "Flapping their wings.",
                        "Contracting and stretching.",
                        "Hopping about.",
                    ),
                    question(
                        "What is the 'trapdoor', which snails use to cover the entrance to " +
                            "their shells called?",
                        0,
                        "An operculum.",
                        "A caldarium.",
                        "A tavernium.",
                    ),
                ),
        ),
    )
